x-veld:
  executable:
    about:
      description: "A NER trainig setup, utilizing spacy3's config system."
      topic:
        - "NLP"
        - "Machine Learning"
    input:
      a:
        type: "files"
        format: "spaCy DocBin"
        content: "Named Entity Recognition gold data" 
        path: /veld/input/train.spacy
        description: "train data"
      b:
        type: "files"
        format: "spaCy DocBin"
        content: "Named Entity Recognition gold data" 
        path: /veld/input/dev.spacy
        description: "dev data"
      c:
        type: "files"
        format: "spaCy DocBin"
        content: "Named Entity Recognition gold data" 
        path: /veld/input/eval.spacy
        description: "eval data"
    output:
      a:
        path: /veld/output/a/
        format: "spacy model"
        kind:
          - "NLP model"
          - "Machine Learning model"
      b:
        path: /veld/output/b/
        format: "txt"
        kind: "log"
        description: "folder for the two log files: train.log and eval.log"

services:
  veld:
    build: .
    volumes:
      - ./:/veld/executable/
    command: >
      bash -c "
      python -m spacy train /veld/executable/config3.cfg --paths.train /veld/input/train.spacy --paths.dev /veld/input/dev.spacy --output /veld/output/a/ |& tee /veld/output/b/train.log
      && python -m spacy evaluate /veld/output/a/model-best/ /veld/input/eval.spacy |& tee /veld/output/b/eval.log
      "

