x-veld:
  executable:
    about:
      description: "A NER trainig setup, utilizing spacy3's config system."
      scope:
        - "NLP"
        - "Machine Learning"
    input:
      "1":
        path: /veld/input/
        format: "spacy DocBin"
        description: "expecting: train.spacy, dev.spacy, eval.spacy."
    output:
      "1":
        path: /veld/output/1/
        format: "spacy model"
        kind:
          - "NLP model"
          - "Machine Learning model"
      "2":
        path: /veld/output/2/
        format: "txt"
        kind: "log"
        description: "folder for the two log files: train.log and eval.log"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    command: >
      bash -c "
      python -m spacy train /veld/executable/config.cfg --output /veld/output/1/m1 |& tee /veld/output/2/train.log
      && python -m spacy evaluate /veld/output/1/m1/model-best/ /veld/input/eval.spacy |& tee /veld/output/2/eval.log
      "

